### ISSUE TITLE
Login error - new Gigya version

### ISSUE THREAD

**Issue by cmik** [cmik/cmik.xbmc#44]
Error appear when login into TFC.tv add-on

> 23:50:37.333 T:23644  NOTICE: [TFC.tv] tfctv.py(1891)::callServiceApi : 'called function with param (/js/gigya.js?apikey=3_ELrVZuv5Q-zPSnY5Gw_GPSTAGdgQCspzCBAVln-mLaUx7qy8xvDwiofK5PU9Xwhy&_=1555278637.33)'
> 23:50:37.468 T:23644   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.AttributeError'>
>                                             Error Contents: 'NoneType' object has no attribute 'group'
>                                             Traceback (most recent call last):
>                                               File "C:\Users\cmik\AppData\Roaming\Kodi\addons\plugin.video.tfctv\default.py", line 64, in <module>
>                                                 from resources.lib.indexers import navigator
>                                               File "C:\Users\cmik\AppData\Roaming\Kodi\addons\plugin.video.tfctv\resources\lib\indexers\navigator.py", line 26, in <module>
>                                                 from resources.lib.sources import tfctv
>                                               File "C:\Users\cmik\AppData\Roaming\Kodi\addons\plugin.video.tfctv\resources\lib\sources\tfctv.py", line 2041, in <module>
>                                                 loginToWebsite()
>                                               File "C:\Users\cmik\AppData\Roaming\Kodi\addons\plugin.video.tfctv\resources\lib\sources\tfctv.py", line 1592, in loginToWebsite
>                                                 gigyaVersion = re.compile('"version":?"([\d.]+)",').search(gigyaHtml).group(1)
>                                             AttributeError: 'NoneType' object has no attribute 'group'
>                                             -->End of Python script error report<--

**Comment by cmik** [comment]
Issue due to new Gigya version string format : 
> gigya.build={"number":2356,"version":"v9.1.40","chico":true};

**Comment by cmik** [comment]
A fix is on the way : 23d22bc
