### ISSUE TITLE
LOG IN ERROR ON KODI LEIA?

### ISSUE THREAD

**Issue by MALCHUSTVKODI** [cmik/cmik.xbmc#47]

**Comment by MALCHUSTVKODI** [comment]
anyone having issues on log in on kodi leia?hello boss cmik,just reporting an error on 
leia 18 ,im having problems logging in?here is the log error ?

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: string index out of range
                                            Traceback (most recent call last):
                                              File "E:\Kodi18leahempty\portable_data\addons\plugin.video.tfctv\default.py", line 83, in <module>
                                                navigator.navigator().showCategories()
                                              File "E:\Kodi18leahempty\portable_data\addons\plugin.video.tfctv\resources\lib\indexers\navigator.py", line 109, in showCategories
                                                categories = tfctv.getCategories()
                                              File "E:\Kodi18leahempty\portable_data\addons\plugin.video.tfctv\resources\lib\sources\tfctv.py", line 484, in getCategories
                                                data = getSiteMenu()
                                              File "E:\Kodi18leahempty\portable_data\addons\plugin.video.tfctv\resources\lib\sources\tfctv.py", line 450, in getSiteMenu
                                                html = callServiceApi(config.uri.get('base'), base_url = config.websiteUrl)
                                              File "E:\Kodi18leahempty\portable_data\addons\plugin.video.tfctv\resources\lib\sources\tfctv.py", line 1946, in callServiceApi
                                                if (tmp[0] == '') or (time.time()-float(tmp[1])>int(control.setting('cacheTTL'))*60):
                                            IndexError: string index out of range
                                            -->End of Python script error report<--

**Comment by Jranns** [comment]
Any news on this login error.?? Same here

**Comment by cmik** [comment]
@MALCHUSTVKODI ,
Sorry for the late reply.
There is a new version 1.3.1.
Can you try and tell if your issue is solved?
If not, you'll have to disable cache in the add-on advanced settings.
Thanks

**Comment by mickadams121** [comment]
Hi please help anyone mrs on my case no 
Tfc specific stream sever I’m using is https://04-vh. Had to set up again but loads menu but won’t play any help would be great thank u

**Comment by cmik** [comment]
@mickadams121,
You can upgrade to the last version if not done yet.
And also disable specific stream server settings.

**Comment by sheryl80** [comment]
Hello CMIK!

I'm having issues with my tfc on kodi for a few months now. Since it started I'm just using my tablet or phone to watch. Today I decided to update my kodi to Leia version and I installed TFC. The problem now ... once I open it it shows a screen that says enter your credentials when I click that it ask for username and password. But then after I enter it shows me Welcome but it is still in the screen. What's going on and I have the new version of Tfc. 

I hope you can help me. Thanks!

**Comment by sheryl80** [comment]
@cmik my tfc is working now but for shows only.  I'm not sure if all movies doesn't work but those few that I tried said it is not supported. The ones I tried are movies from I want TV and the new ones like To Love Some buddy and Sid and Aya

**Comment by mickadams121** [comment]
Hi anyone having problems logging into tfc lost everything

**Comment by MALCHUSTVKODI** [comment]
Anyone having log in issues on bOTh kodi 18.3 and kodi 17.6 on the latest update version 1.3.2 of TFC ADDON .ON A FRESH INSTALL , OR is it just me??anyone pls..??on my laptop windows 10 kodi 17.6  its working ok @cmik tried on fire stick 2nd gen thats where i get error logging in...see if i can find a way to upload log error?

**Comment by arnel300** [comment]
no problems here

**Comment by MALCHUSTVKODI** [comment]
2019-08-24 22:54:59.681 T:12427   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/default.py", line 64, in <module>
                                                from resources.lib.indexers import navigator
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/indexers/navigator.py", line 26, in <module>
                                                from resources.lib.sources import tfctv
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 2099, in <module>
                                                loginToWebsite()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 1628, in loginToWebsite
                                                gigyaVersion = re.compile('"version":?"(.+)",').search(gigyaHtml).group(1)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
2019-08-24 22:54:59.853 T:12417   ERROR: GetDirectory - Error getting plugin://plugin.video.tfctv/
2019-08-24 22:54:59.888 T:11909   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tfctv/) failed

**Comment by MALCHUSTVKODI** [comment]
above is the log error @cmik..@arnel300 can you tell me what device you use? try a fresh install of tfc fresh install nothing on only tfc addon?has to be android fire stick kodi 17.6 or kodi 18,3,,cheers ..salamat po ng marami @cmik

**Comment by arnel300** [comment]
firestick... clean install of 18.3 with nolimits build...

**Comment by bidi1268** [comment]
Hello there. Need help please. Im using firestick with kodi 18.4 Leia cant log in on tfc.tv, always appear check log for more information. Thanks in advance

**Comment by cmik** [comment]
@bidi1268
Can you test with the newly version 1.3.3?

**Comment by bidi1268** [comment]
Thank u very much Cmik. Now its working again👍👍👍

**Comment by mickadams121** [comment]
Good evening me again wonder if you can help updated to latest 141 but
won’t work hope you can help regards mick
