### ISSUE TITLE
Cannot access addon as of today

### ISSUE THREAD

**Issue by sdstreams** [cmik/cmik.xbmc#51]
TFC.tv error when trying to access the addon as of today. is anyone else experiencing this?

**Comment by seana213** [comment]
Tfc.tv error check the log for more information today. I can't login to the addon

**Comment by whoopderitis** [comment]
Having the same issue.

**Comment by ironhawk911** [comment]
I am having same issue as well. Checked the KODI logs and this is the error I found in one of python file. 

`AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by bidi1268** [comment]
same here😔 can’t log in to the addon

**Comment by cmik** [comment]
Hi all,
The fix is in the new version 1.3.3 https://github.com/cmik/cmik.xbmc/commit/837afffae4c74f5ace230d67894850c5e5bbf722 
Thanks in advance for your feedbacks.

**Comment by Jranns** [comment]
Login error using latest version 1.3.3. . Cant login

**Comment by Ilovetfc** [comment]
same here😔 can’t log in to tfc.tv addon version 1.3.3

**Comment by MALCHUSTVKODI** [comment]
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "E:\Kodiport17test\portable_data\addons\plugin.video.tfctv\default.py", line 74, in <module>
                                                navigator.navigator().showEpisodes(url, page, params.get('parentid', -1), params.get('year', ''))
                                              File "E:\Kodiport17test\portable_data\addons\plugin.video.tfctv\resources\lib\indexers\navigator.py", line 160, in showEpisodes
                                                (episodes, nextPage) = tfctv.getEpisodesPerPage(showId, parentId, year, page, itemsPerPage)
                                              File "E:\Kodiport17test\portable_data\addons\plugin.video.tfctv\resources\lib\sources\tfctv.py", line 979, in getEpisodesPerPage
                                                showDetails = getShow(showId, parentId, year)
                                              File "E:\Kodiport17test\portable_data\addons\plugin.video.tfctv\resources\lib\sources\tfctv.py", line 927, in getShow
                                                nbEpisodes = int(re.compile('\(([0-9]+)\)', re.IGNORECASE).search(common.parseDOM(html, "h2", attrs = { 'class' : 'episode-list-showp' })[0]).group(1))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--

**Comment by MALCHUSTVKODI** [comment]
Just reporting an error on kodi18.4 on FTV device  ,,able.to log in but gives error when u play shows...here is the log hope it helps. @cmik salamat po ng marami...

**Comment by MALCHUSTVKODI** [comment]
2019-09-13 20:03:02.604 T:25614   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2019-09-13 20:03:03.894 T:26015   ERROR: 127.0.0.1 - - [13/Sep/2019 20:03:03] "GET /healthcheck HTTP/1.1" 200 -
2019-09-13 20:03:25.273 T:26015   ERROR: 127.0.0.1 - - [13/Sep/2019 20:03:25] "GET /healthcheck HTTP/1.1" 200 -
2019-09-13 20:03:29.548 T:26532   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/default.py", line 80, in <module>
                                                tfctv.playEpisode(url, title, thumbnail, params.get('bandwidth', False))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 50, in playEpisode
                                                episodeDetails = getMediaInfo(episode, name, thumbnail, bandwidth)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 106, in getMediaInfo
                                                mediaInfo = getMediaInfoFromWebsite(episodeId, bandwidth)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 236, in getMediaInfoFromWebsite
                                                if 'media' in episodeDetails and 'source' in episodeDetails['media'] and 'src' in episodeDetails['media']['source'][0] :
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
2019-09-13 20:03:29.858 T:25614   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tfctv/?url=192556&mode=4&name=Bandila+-+Sep+13%2C+2019&page=1&thumbnail=https%3A%2F%2Fimg.tfc.tv%2Fxcms%2Fepisodeimages%2F192556%2F20190913-bandila-487.jpg&title=Bandila - Sep 13, 2019]
2019-09-13 20:03:37.000 T:26015   ERROR: 127.0.0.1 - - [13/Sep/2019 20:03:37] "GET /healthcheck HTTP/1.1" 200 -
2019-09-13 20:03:41.087 T:26573   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/default.py", line 80, in <module>
                                                tfctv.playEpisode(url, title, thumbnail, params.get('bandwidth', False))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 50, in playEpisode
                                                episodeDetails = getMediaInfo(episode, name, thumbnail, bandwidth)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 106, in getMediaInfo
                                                mediaInfo = getMediaInfoFromWebsite(episodeId, bandwidth)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tfctv/resources/lib/sources/tfctv.py", line 236, in getMediaInfoFromWebsite
                                                if 'media' in episodeDetails and 'source' in episodeDetails['media'] and 'src' in episodeDetails['media']['source'][0] :
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--

**Comment by cmik** [comment]
Hi @MALCHUSTVKODI ,
Which media are you trying to play?
It seems it doesn't have any source data to be used.

**Comment by bumpz1975** [comment]
Hi same issue,I can log in successfully but it just stops there...does not open the menu

**Comment by cmik** [comment]
@MALCHUSTVKODI ,
Bandila episode of sept 13, 2019 is working on my side. It seems it was TFC but now it is fixed.
I've added a check on version 1.4.0 to prevent this type of issue (checking the error code if any)

**Comment by cmik** [comment]
@bumpz1975 ,
Can you please be more precise on your issue?
Can you share some logs?
Thanks in advance.
